### ISSUE TITLE
Desactivate the button product page

### ISSUE THREAD

**Issue by StefBrito** [oystparis/oyst-1click-magento#320]

**Comment by mehdichaouch** [comment]
@rus-daniel the goal of this issue is to disable the product page button in the same way as the checkout car button.
<img width="517" alt="capture d ecran 2018-04-12 a 15 33 39" src="https://user-images.githubusercontent.com/861701/38680604-ff344480-3e66-11e8-922b-ea80ac53a290.png">

like checkout cart:
<img width="542" alt="capture d ecran 2018-04-12 a 15 31 15" src="https://user-images.githubusercontent.com/861701/38680618-08b474c6-3e67-11e8-8957-72a64a9ea424.png">
